# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from serial_imu/Imu_0x62_msg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import serial_imu.msg
import std_msgs.msg

class Imu_0x62_msg(genpy.Message):
  _md5sum = "ade2d5aa1eaff1ee78a6de59cc0d4424"
  _type = "serial_imu/Imu_0x62_msg"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """#62 data_package
Header header
uint8 gw_tag
uint8 gw_id
uint8 gw_n
Imu_0x91_msg[] node
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: serial_imu/Imu_0x91_msg
#90 91 data_package
Header header
uint8 tag
uint8 bitmap
uint8 id
uint32 times
uint32 frame_rate
float32 acc_x
float32 acc_y
float32 acc_z
float32 gyr_x
float32 gyr_y
float32 gyr_z
float32 mag_x
float32 mag_y
float32 mag_z
float32 eul_r
float32 eul_p
float32 eul_y
float32 quat_w
float32 quat_x
float32 quat_y
float32 quat_z
"""
  __slots__ = ['header','gw_tag','gw_id','gw_n','node']
  _slot_types = ['std_msgs/Header','uint8','uint8','uint8','serial_imu/Imu_0x91_msg[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,gw_tag,gw_id,gw_n,node

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Imu_0x62_msg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.gw_tag is None:
        self.gw_tag = 0
      if self.gw_id is None:
        self.gw_id = 0
      if self.gw_n is None:
        self.gw_n = 0
      if self.node is None:
        self.node = []
    else:
      self.header = std_msgs.msg.Header()
      self.gw_tag = 0
      self.gw_id = 0
      self.gw_n = 0
      self.node = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3B().pack(_x.gw_tag, _x.gw_id, _x.gw_n))
      length = len(self.node)
      buff.write(_struct_I.pack(length))
      for val1 in self.node:
        _v1 = val1.header
        _x = _v1.seq
        buff.write(_get_struct_I().pack(_x))
        _v2 = _v1.stamp
        _x = _v2
        buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
        _x = _v1.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_3B2I16f().pack(_x.tag, _x.bitmap, _x.id, _x.times, _x.frame_rate, _x.acc_x, _x.acc_y, _x.acc_z, _x.gyr_x, _x.gyr_y, _x.gyr_z, _x.mag_x, _x.mag_y, _x.mag_z, _x.eul_r, _x.eul_p, _x.eul_y, _x.quat_w, _x.quat_x, _x.quat_y, _x.quat_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.node is None:
        self.node = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 3
      (_x.gw_tag, _x.gw_id, _x.gw_n,) = _get_struct_3B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.node = []
      for i in range(0, length):
        val1 = serial_imu.msg.Imu_0x91_msg()
        _v3 = val1.header
        start = end
        end += 4
        (_v3.seq,) = _get_struct_I().unpack(str[start:end])
        _v4 = _v3.stamp
        _x = _v4
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v3.frame_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v3.frame_id = str[start:end]
        _x = val1
        start = end
        end += 75
        (_x.tag, _x.bitmap, _x.id, _x.times, _x.frame_rate, _x.acc_x, _x.acc_y, _x.acc_z, _x.gyr_x, _x.gyr_y, _x.gyr_z, _x.mag_x, _x.mag_y, _x.mag_z, _x.eul_r, _x.eul_p, _x.eul_y, _x.quat_w, _x.quat_x, _x.quat_y, _x.quat_z,) = _get_struct_3B2I16f().unpack(str[start:end])
        self.node.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3B().pack(_x.gw_tag, _x.gw_id, _x.gw_n))
      length = len(self.node)
      buff.write(_struct_I.pack(length))
      for val1 in self.node:
        _v5 = val1.header
        _x = _v5.seq
        buff.write(_get_struct_I().pack(_x))
        _v6 = _v5.stamp
        _x = _v6
        buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
        _x = _v5.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_3B2I16f().pack(_x.tag, _x.bitmap, _x.id, _x.times, _x.frame_rate, _x.acc_x, _x.acc_y, _x.acc_z, _x.gyr_x, _x.gyr_y, _x.gyr_z, _x.mag_x, _x.mag_y, _x.mag_z, _x.eul_r, _x.eul_p, _x.eul_y, _x.quat_w, _x.quat_x, _x.quat_y, _x.quat_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.node is None:
        self.node = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 3
      (_x.gw_tag, _x.gw_id, _x.gw_n,) = _get_struct_3B().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.node = []
      for i in range(0, length):
        val1 = serial_imu.msg.Imu_0x91_msg()
        _v7 = val1.header
        start = end
        end += 4
        (_v7.seq,) = _get_struct_I().unpack(str[start:end])
        _v8 = _v7.stamp
        _x = _v8
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v7.frame_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v7.frame_id = str[start:end]
        _x = val1
        start = end
        end += 75
        (_x.tag, _x.bitmap, _x.id, _x.times, _x.frame_rate, _x.acc_x, _x.acc_y, _x.acc_z, _x.gyr_x, _x.gyr_y, _x.gyr_z, _x.mag_x, _x.mag_y, _x.mag_z, _x.eul_r, _x.eul_p, _x.eul_y, _x.quat_w, _x.quat_x, _x.quat_y, _x.quat_z,) = _get_struct_3B2I16f().unpack(str[start:end])
        self.node.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_3B = None
def _get_struct_3B():
    global _struct_3B
    if _struct_3B is None:
        _struct_3B = struct.Struct("<3B")
    return _struct_3B
_struct_3B2I16f = None
def _get_struct_3B2I16f():
    global _struct_3B2I16f
    if _struct_3B2I16f is None:
        _struct_3B2I16f = struct.Struct("<3B2I16f")
    return _struct_3B2I16f
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
