// Generated by gencpp from file serial_imu/Imu_0x91_msg.msg
// DO NOT EDIT!


#ifndef SERIAL_IMU_MESSAGE_IMU_0X91_MSG_H
#define SERIAL_IMU_MESSAGE_IMU_0X91_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace serial_imu
{
template <class ContainerAllocator>
struct Imu_0x91_msg_
{
  typedef Imu_0x91_msg_<ContainerAllocator> Type;

  Imu_0x91_msg_()
    : header()
    , tag(0)
    , bitmap(0)
    , id(0)
    , times(0)
    , frame_rate(0)
    , acc_x(0.0)
    , acc_y(0.0)
    , acc_z(0.0)
    , gyr_x(0.0)
    , gyr_y(0.0)
    , gyr_z(0.0)
    , mag_x(0.0)
    , mag_y(0.0)
    , mag_z(0.0)
    , eul_r(0.0)
    , eul_p(0.0)
    , eul_y(0.0)
    , quat_w(0.0)
    , quat_x(0.0)
    , quat_y(0.0)
    , quat_z(0.0)  {
    }
  Imu_0x91_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , tag(0)
    , bitmap(0)
    , id(0)
    , times(0)
    , frame_rate(0)
    , acc_x(0.0)
    , acc_y(0.0)
    , acc_z(0.0)
    , gyr_x(0.0)
    , gyr_y(0.0)
    , gyr_z(0.0)
    , mag_x(0.0)
    , mag_y(0.0)
    , mag_z(0.0)
    , eul_r(0.0)
    , eul_p(0.0)
    , eul_y(0.0)
    , quat_w(0.0)
    , quat_x(0.0)
    , quat_y(0.0)
    , quat_z(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _tag_type;
  _tag_type tag;

   typedef uint8_t _bitmap_type;
  _bitmap_type bitmap;

   typedef uint8_t _id_type;
  _id_type id;

   typedef uint32_t _times_type;
  _times_type times;

   typedef uint32_t _frame_rate_type;
  _frame_rate_type frame_rate;

   typedef float _acc_x_type;
  _acc_x_type acc_x;

   typedef float _acc_y_type;
  _acc_y_type acc_y;

   typedef float _acc_z_type;
  _acc_z_type acc_z;

   typedef float _gyr_x_type;
  _gyr_x_type gyr_x;

   typedef float _gyr_y_type;
  _gyr_y_type gyr_y;

   typedef float _gyr_z_type;
  _gyr_z_type gyr_z;

   typedef float _mag_x_type;
  _mag_x_type mag_x;

   typedef float _mag_y_type;
  _mag_y_type mag_y;

   typedef float _mag_z_type;
  _mag_z_type mag_z;

   typedef float _eul_r_type;
  _eul_r_type eul_r;

   typedef float _eul_p_type;
  _eul_p_type eul_p;

   typedef float _eul_y_type;
  _eul_y_type eul_y;

   typedef float _quat_w_type;
  _quat_w_type quat_w;

   typedef float _quat_x_type;
  _quat_x_type quat_x;

   typedef float _quat_y_type;
  _quat_y_type quat_y;

   typedef float _quat_z_type;
  _quat_z_type quat_z;





  typedef boost::shared_ptr< ::serial_imu::Imu_0x91_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial_imu::Imu_0x91_msg_<ContainerAllocator> const> ConstPtr;

}; // struct Imu_0x91_msg_

typedef ::serial_imu::Imu_0x91_msg_<std::allocator<void> > Imu_0x91_msg;

typedef boost::shared_ptr< ::serial_imu::Imu_0x91_msg > Imu_0x91_msgPtr;
typedef boost::shared_ptr< ::serial_imu::Imu_0x91_msg const> Imu_0x91_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serial_imu::Imu_0x91_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serial_imu::Imu_0x91_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::serial_imu::Imu_0x91_msg_<ContainerAllocator1> & lhs, const ::serial_imu::Imu_0x91_msg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.tag == rhs.tag &&
    lhs.bitmap == rhs.bitmap &&
    lhs.id == rhs.id &&
    lhs.times == rhs.times &&
    lhs.frame_rate == rhs.frame_rate &&
    lhs.acc_x == rhs.acc_x &&
    lhs.acc_y == rhs.acc_y &&
    lhs.acc_z == rhs.acc_z &&
    lhs.gyr_x == rhs.gyr_x &&
    lhs.gyr_y == rhs.gyr_y &&
    lhs.gyr_z == rhs.gyr_z &&
    lhs.mag_x == rhs.mag_x &&
    lhs.mag_y == rhs.mag_y &&
    lhs.mag_z == rhs.mag_z &&
    lhs.eul_r == rhs.eul_r &&
    lhs.eul_p == rhs.eul_p &&
    lhs.eul_y == rhs.eul_y &&
    lhs.quat_w == rhs.quat_w &&
    lhs.quat_x == rhs.quat_x &&
    lhs.quat_y == rhs.quat_y &&
    lhs.quat_z == rhs.quat_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::serial_imu::Imu_0x91_msg_<ContainerAllocator1> & lhs, const ::serial_imu::Imu_0x91_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace serial_imu

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::serial_imu::Imu_0x91_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_imu::Imu_0x91_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_imu::Imu_0x91_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_imu::Imu_0x91_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_imu::Imu_0x91_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_imu::Imu_0x91_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serial_imu::Imu_0x91_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2f291d45ec45967d294cfba2fb713db6";
  }

  static const char* value(const ::serial_imu::Imu_0x91_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2f291d45ec45967dULL;
  static const uint64_t static_value2 = 0x294cfba2fb713db6ULL;
};

template<class ContainerAllocator>
struct DataType< ::serial_imu::Imu_0x91_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serial_imu/Imu_0x91_msg";
  }

  static const char* value(const ::serial_imu::Imu_0x91_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serial_imu::Imu_0x91_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#90 91 data_package\n"
"Header header\n"
"uint8 tag\n"
"uint8 bitmap\n"
"uint8 id\n"
"uint32 times\n"
"uint32 frame_rate\n"
"float32 acc_x\n"
"float32 acc_y\n"
"float32 acc_z\n"
"float32 gyr_x\n"
"float32 gyr_y\n"
"float32 gyr_z\n"
"float32 mag_x\n"
"float32 mag_y\n"
"float32 mag_z\n"
"float32 eul_r\n"
"float32 eul_p\n"
"float32 eul_y\n"
"float32 quat_w\n"
"float32 quat_x\n"
"float32 quat_y\n"
"float32 quat_z\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::serial_imu::Imu_0x91_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serial_imu::Imu_0x91_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.tag);
      stream.next(m.bitmap);
      stream.next(m.id);
      stream.next(m.times);
      stream.next(m.frame_rate);
      stream.next(m.acc_x);
      stream.next(m.acc_y);
      stream.next(m.acc_z);
      stream.next(m.gyr_x);
      stream.next(m.gyr_y);
      stream.next(m.gyr_z);
      stream.next(m.mag_x);
      stream.next(m.mag_y);
      stream.next(m.mag_z);
      stream.next(m.eul_r);
      stream.next(m.eul_p);
      stream.next(m.eul_y);
      stream.next(m.quat_w);
      stream.next(m.quat_x);
      stream.next(m.quat_y);
      stream.next(m.quat_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Imu_0x91_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serial_imu::Imu_0x91_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serial_imu::Imu_0x91_msg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "tag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.tag);
    s << indent << "bitmap: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bitmap);
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "times: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.times);
    s << indent << "frame_rate: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.frame_rate);
    s << indent << "acc_x: ";
    Printer<float>::stream(s, indent + "  ", v.acc_x);
    s << indent << "acc_y: ";
    Printer<float>::stream(s, indent + "  ", v.acc_y);
    s << indent << "acc_z: ";
    Printer<float>::stream(s, indent + "  ", v.acc_z);
    s << indent << "gyr_x: ";
    Printer<float>::stream(s, indent + "  ", v.gyr_x);
    s << indent << "gyr_y: ";
    Printer<float>::stream(s, indent + "  ", v.gyr_y);
    s << indent << "gyr_z: ";
    Printer<float>::stream(s, indent + "  ", v.gyr_z);
    s << indent << "mag_x: ";
    Printer<float>::stream(s, indent + "  ", v.mag_x);
    s << indent << "mag_y: ";
    Printer<float>::stream(s, indent + "  ", v.mag_y);
    s << indent << "mag_z: ";
    Printer<float>::stream(s, indent + "  ", v.mag_z);
    s << indent << "eul_r: ";
    Printer<float>::stream(s, indent + "  ", v.eul_r);
    s << indent << "eul_p: ";
    Printer<float>::stream(s, indent + "  ", v.eul_p);
    s << indent << "eul_y: ";
    Printer<float>::stream(s, indent + "  ", v.eul_y);
    s << indent << "quat_w: ";
    Printer<float>::stream(s, indent + "  ", v.quat_w);
    s << indent << "quat_x: ";
    Printer<float>::stream(s, indent + "  ", v.quat_x);
    s << indent << "quat_y: ";
    Printer<float>::stream(s, indent + "  ", v.quat_y);
    s << indent << "quat_z: ";
    Printer<float>::stream(s, indent + "  ", v.quat_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_IMU_MESSAGE_IMU_0X91_MSG_H
