// Generated by gencpp from file serial_imu/Imu_0x62_msg.msg
// DO NOT EDIT!


#ifndef SERIAL_IMU_MESSAGE_IMU_0X62_MSG_H
#define SERIAL_IMU_MESSAGE_IMU_0X62_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <serial_imu/Imu_0x91_msg.h>

namespace serial_imu
{
template <class ContainerAllocator>
struct Imu_0x62_msg_
{
  typedef Imu_0x62_msg_<ContainerAllocator> Type;

  Imu_0x62_msg_()
    : header()
    , gw_tag(0)
    , gw_id(0)
    , gw_n(0)
    , node()  {
    }
  Imu_0x62_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , gw_tag(0)
    , gw_id(0)
    , gw_n(0)
    , node(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _gw_tag_type;
  _gw_tag_type gw_tag;

   typedef uint8_t _gw_id_type;
  _gw_id_type gw_id;

   typedef uint8_t _gw_n_type;
  _gw_n_type gw_n;

   typedef std::vector< ::serial_imu::Imu_0x91_msg_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::serial_imu::Imu_0x91_msg_<ContainerAllocator> >::other >  _node_type;
  _node_type node;





  typedef boost::shared_ptr< ::serial_imu::Imu_0x62_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial_imu::Imu_0x62_msg_<ContainerAllocator> const> ConstPtr;

}; // struct Imu_0x62_msg_

typedef ::serial_imu::Imu_0x62_msg_<std::allocator<void> > Imu_0x62_msg;

typedef boost::shared_ptr< ::serial_imu::Imu_0x62_msg > Imu_0x62_msgPtr;
typedef boost::shared_ptr< ::serial_imu::Imu_0x62_msg const> Imu_0x62_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serial_imu::Imu_0x62_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serial_imu::Imu_0x62_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::serial_imu::Imu_0x62_msg_<ContainerAllocator1> & lhs, const ::serial_imu::Imu_0x62_msg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.gw_tag == rhs.gw_tag &&
    lhs.gw_id == rhs.gw_id &&
    lhs.gw_n == rhs.gw_n &&
    lhs.node == rhs.node;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::serial_imu::Imu_0x62_msg_<ContainerAllocator1> & lhs, const ::serial_imu::Imu_0x62_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace serial_imu

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::serial_imu::Imu_0x62_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_imu::Imu_0x62_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_imu::Imu_0x62_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_imu::Imu_0x62_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_imu::Imu_0x62_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_imu::Imu_0x62_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serial_imu::Imu_0x62_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ade2d5aa1eaff1ee78a6de59cc0d4424";
  }

  static const char* value(const ::serial_imu::Imu_0x62_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xade2d5aa1eaff1eeULL;
  static const uint64_t static_value2 = 0x78a6de59cc0d4424ULL;
};

template<class ContainerAllocator>
struct DataType< ::serial_imu::Imu_0x62_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serial_imu/Imu_0x62_msg";
  }

  static const char* value(const ::serial_imu::Imu_0x62_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serial_imu::Imu_0x62_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#62 data_package\n"
"Header header\n"
"uint8 gw_tag\n"
"uint8 gw_id\n"
"uint8 gw_n\n"
"Imu_0x91_msg[] node\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: serial_imu/Imu_0x91_msg\n"
"#90 91 data_package\n"
"Header header\n"
"uint8 tag\n"
"uint8 bitmap\n"
"uint8 id\n"
"uint32 times\n"
"uint32 frame_rate\n"
"float32 acc_x\n"
"float32 acc_y\n"
"float32 acc_z\n"
"float32 gyr_x\n"
"float32 gyr_y\n"
"float32 gyr_z\n"
"float32 mag_x\n"
"float32 mag_y\n"
"float32 mag_z\n"
"float32 eul_r\n"
"float32 eul_p\n"
"float32 eul_y\n"
"float32 quat_w\n"
"float32 quat_x\n"
"float32 quat_y\n"
"float32 quat_z\n"
;
  }

  static const char* value(const ::serial_imu::Imu_0x62_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serial_imu::Imu_0x62_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.gw_tag);
      stream.next(m.gw_id);
      stream.next(m.gw_n);
      stream.next(m.node);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Imu_0x62_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serial_imu::Imu_0x62_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serial_imu::Imu_0x62_msg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "gw_tag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gw_tag);
    s << indent << "gw_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gw_id);
    s << indent << "gw_n: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gw_n);
    s << indent << "node[]" << std::endl;
    for (size_t i = 0; i < v.node.size(); ++i)
    {
      s << indent << "  node[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::serial_imu::Imu_0x91_msg_<ContainerAllocator> >::stream(s, indent + "    ", v.node[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_IMU_MESSAGE_IMU_0X62_MSG_H
