// Generated by gencpp from file move_robot/state.msg
// DO NOT EDIT!


#ifndef MOVE_ROBOT_MESSAGE_STATE_H
#define MOVE_ROBOT_MESSAGE_STATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace move_robot
{
template <class ContainerAllocator>
struct state_
{
  typedef state_<ContainerAllocator> Type;

  state_()
    : id(0)
    , state(0)  {
    }
  state_(const ContainerAllocator& _alloc)
    : id(0)
    , state(0)  {
  (void)_alloc;
    }



   typedef int16_t _id_type;
  _id_type id;

   typedef int8_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::move_robot::state_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::move_robot::state_<ContainerAllocator> const> ConstPtr;

}; // struct state_

typedef ::move_robot::state_<std::allocator<void> > state;

typedef boost::shared_ptr< ::move_robot::state > statePtr;
typedef boost::shared_ptr< ::move_robot::state const> stateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::move_robot::state_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::move_robot::state_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::move_robot::state_<ContainerAllocator1> & lhs, const ::move_robot::state_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::move_robot::state_<ContainerAllocator1> & lhs, const ::move_robot::state_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace move_robot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::move_robot::state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::move_robot::state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_robot::state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::move_robot::state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_robot::state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::move_robot::state_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::move_robot::state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a8661fa608fa36fba2ec658a57a3be9f";
  }

  static const char* value(const ::move_robot::state_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa8661fa608fa36fbULL;
  static const uint64_t static_value2 = 0xa2ec658a57a3be9fULL;
};

template<class ContainerAllocator>
struct DataType< ::move_robot::state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "move_robot/state";
  }

  static const char* value(const ::move_robot::state_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::move_robot::state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 id\n"
"int8 state\n"
;
  }

  static const char* value(const ::move_robot::state_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::move_robot::state_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct state_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::move_robot::state_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::move_robot::state_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.id);
    s << indent << "state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVE_ROBOT_MESSAGE_STATE_H
