(cl:in-package move_robot-msg)
(cl:export '(VOLTAGE-VAL
          VOLTAGE
          CURRENT-VAL
          CURRENT
          RELATIVESOC1-VAL
          RELATIVESOC1
          RELATIVESOC2-VAL
          RELATIVESOC2
          RELATIVESOC3-VAL
          RELATIVESOC3
          RELATIVESOC4-VAL
          RELATIVESOC4
          ABSOLUTESOC1-VAL
          ABSOLUTESOC1
          ABSOLUTESOC2-VAL
          ABSOLUTESOC2
          ABSOLUTESOC3-VAL
          ABSOLUTESOC3
          ABSOLUTESOC4-VAL
          ABSOLUTESOC4
          TEMP1-VAL
          TEMP1
          TEMP2-VAL
          TEMP2
          TEMP3-VAL
          TEMP3
          TEMP4-VAL
          TEMP4
))